CircleCI Commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,18 +23,23 @@ jobs:
       - run:
           name: Configure CMake
           command: |
-            mkdir -p seer/src/build
-            cd seer/src/build
-            cmake -DQTVERSION=QT5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5 ..
+            if [ -f seer/CMakeLists.txt ]; then
+              mkdir -p seer/build
+              cd seer/build
+              cmake -DQTVERSION=QT5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5 ..
+            else
+              echo "CMakeLists.txt not found in the expected location."
+              exit 1
+            fi
       - run:
           name: Build SeerGDB
           command: |
-            cd seer/src/build
+            cd seer/build
             make seergdb
       - run:
           name: Install SeerGDB
           command: |
-            cd seer/src/build
+            cd seer/build
             sudo make install
       - run:
           name: Package as .deb
